{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","text":"KeyboardInputViewController"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The keyboard input controller to use."}]}],"name":"controller"}],"kind":"parameters"}],"kind":"symbol","metadata":{"modules":[{"name":"KeyboardKitPro"}],"title":"init(controller:)","roleHeading":"Initializer","role":"symbol","externalID":"s:14KeyboardKitPro08StandardA13ActionHandlerC10controllerAcA0A19InputViewControllerC_tcfc","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"controller","kind":"externalParam"},{"kind":"text","text":": "},{"text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/init(controller:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/init(controller:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler"]]},"abstract":[{"type":"text","text":"Create a standard keyboard action handler."}],"sections":[],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","kind":"symbol","title":"KeyboardInputViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This class extends ","type":"text"},{"type":"codeVoice","code":"UIInputViewController"},{"text":" with KeyboardKit","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"specific functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler/init(controller:)":{"kind":"symbol","abstract":[{"text":"Create a standard keyboard action handler.","type":"text"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler\/init(controller:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"controller","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler\/init(controller:)","title":"init(controller:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","kind":"symbol","abstract":[{"text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardActionHandler":{"kind":"symbol","abstract":[{"type":"text","text":"This standard keyboard action handler is used by default by"},{"text":" ","type":"text"},{"type":"text","text":"KeyboardKit and provides a standard way of handling actions."}],"type":"topic","url":"\/documentation\/keyboardkitpro\/standardkeyboardactionhandler","navigatorTitle":[{"text":"StandardKeyboardActionHandler","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StandardKeyboardActionHandler"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardActionHandler","title":"StandardKeyboardActionHandler"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"KeyboardInputViewController","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1StandardKeyboardActionHandler\/title","value":"StandardKeyboardActionHandler"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1StandardKeyboardActionHandler\/fragments","value":[{"text":"StandardKeyboardActionHandler","kind":"identifier"}],"op":"replace"}]}]}