{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","interfaceLanguage":"swift"},"kind":"article","sections":[],"metadata":{"images":[{"identifier":"Page.png","type":"card"}],"color":{"standardColorIdentifier":"blue"},"modules":[{"name":"KeyboardKitPro"}],"title":"Colors","roleHeading":"Article","role":"article"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"seeAlsoSections":[{"generated":true,"title":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/keyboardkitpro\/colors-article"]},{"paths":["\/documentation\/keyboardkitpro\/colors-article"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"This article describes the KeyboardKit color engine.","type":"text"}],"primaryContentSections":[{"content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit provides additional, keyboard-specific colors that make it easy to apply a keyboard style that mimics the native style."}]},{"type":"heading","level":2,"anchor":"Color-Extensions","text":"Color Extensions"},{"inlineContent":[{"type":"text","text":"KeyboardKit has additional colors that aim to match native iOS system colors, for instance "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Color\/keyboardBackground","type":"reference","isActive":true},{"type":"text","text":". See "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Color","isActive":true,"type":"reference"},{"type":"text","text":" for a full list of additional colors that are provided by the library."}],"type":"paragraph"},{"inlineContent":[{"text":"Colors without the ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"ForDarkAppearance"}]},{"text":" name suffix support both light & dark mode, while colors with the suffix are meant to be used for dark appearance keyboards in light mode.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"KeyboardKit also has contextual color functions that take a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext"},{"text":", for instance ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Color\/keyboardBackground(for:)","isActive":true},{"type":"text","text":" and base the color on the context. It’s recommended to use these functions instead of the raw color values."}],"type":"paragraph"},{"level":2,"type":"heading","text":"Important about keyboards and colors","anchor":"Important-about-keyboards-and-colors"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you take a closer look at some of these keyboard-specific colors, you will notice that some are semi-transparent. The reason for this is to work around a system bug in iOS."}]},{"type":"paragraph","inlineContent":[{"text":"iOS namely provide keyboard extensions with an invalid color scheme when it’s used with a dark appearance text field. iOS will say that the color scheme is ","type":"text"},{"code":".dark","type":"codeVoice"},{"type":"text","text":", even if the system color scheme is light."}]},{"type":"paragraph","inlineContent":[{"text":"Since dark appearance keyboards in light mode look quite different from keyboards in dark mode, this bug makes it impossible to apply the correct style, since it’s impossible to determine if the system uses light or dark mode.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"To work around this bug, some colors use a semi-transparent color with an opacity that aims to look good in both light and dark mode.","type":"text"}]},{"inlineContent":[{"text":"This has been ","type":"text"},{"isActive":true,"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit\/issues\/305","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"role":"article","title":"Styling","abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/styling-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"role":"article","title":"Localization","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/localization-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","title":"Device Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","role":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit device utilities.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"title":"Callouts","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/callouts-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"role":"article","title":"Previews","abstract":[{"text":"This article describes the KeyboardKit preview engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/previews-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/Color/keyboardBackground":{"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Color\/keyboardBackground","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyboardBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Color","preciseIdentifier":"s:7SwiftUI5ColorV"}],"type":"topic","title":"keyboardBackground","abstract":[{"text":"The standard keyboard background color.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/swiftui\/color\/keyboardbackground","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"title":"KeyboardContext","url":"\/documentation\/keyboardkitpro\/keyboardcontext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","type":"topic","abstract":[{"type":"text","text":"This class provides keyboard extensions with contextual and"},{"text":" ","type":"text"},{"text":"observable information about the keyboard extension.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/ai-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"Page.png":{"identifier":"Page.png","type":"image","variants":[{"url":"\/images\/Page.png","traits":["1x","light"]}],"alt":"Page icon"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Routing-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit text routing engine."}],"title":"Text Routing","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/text-routing-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"title":"Emojis","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"title":"Gestures","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"role":"article","abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"title":"Autocomplete","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","kind":"article","url":"\/documentation\/keyboardkitpro\/autocomplete-article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"role":"article","title":"Themes","abstract":[{"text":"This article describes the KeyboardKit theme engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/themes-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"role":"article","title":"Feedback","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Images-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard image engine."}],"title":"Images","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/images-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/State-Article":{"role":"article","title":"State","abstract":[{"text":"This article describes the KeyboardKit state engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/state-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/Color":{"title":"Color","navigatorTitle":[{"kind":"identifier","text":"Color"}],"url":"\/documentation\/keyboardkitpro\/swiftui\/color","type":"topic","abstract":[{"text":"This extension extends ","type":"text"},{"type":"codeVoice","code":"Color"},{"text":" with codable capabilities.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Color","kind":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Color","preciseIdentifier":"s:7SwiftUI5ColorV"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials":{"role":"article","title":"Essentials","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","type":"topic","url":"\/documentation\/keyboardkitpro\/essentials","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"role":"article","title":"Navigation","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"https://github.com/KeyboardKit/KeyboardKit/issues/305":{"type":"link","titleInlineContent":[{"text":"reported to Apple","type":"text"}],"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKit\/issues\/305","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKit\/issues\/305","title":"reported to Apple"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"title":"Layout","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/layout-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}],"title":"Proxy Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/proxy-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"role":"article","title":"External Keyboards","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","kind":"symbol","abstract":[{"text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"role":"article","title":"Settings","abstract":[{"text":"This article describes the KeyboardKit settings engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/settings-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/Color/keyboardBackground(for:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Color\/keyboardBackground(for:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The standard keyboard button background color."}],"url":"\/documentation\/keyboardkitpro\/swiftui\/color\/keyboardbackground(for:)","title":"keyboardBackground(for:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyboardBackground"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"KeyboardContext","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A7ContextC"},{"kind":"text","text":") -> "},{"text":"Color","preciseIdentifier":"s:7SwiftUI5ColorV","kind":"typeIdentifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"role":"article","title":"Actions","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"value":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Features"}],"op":"replace","path":"\/seeAlsoSections"}]}]}