{"kind":"article","primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"text":"KeyboardKit provides additional, keyboard-specific images that make it easy to apply a keyboard style that mimics the native style.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"👑 "},{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","type":"reference","isActive":true},{"text":" provides vectorized assets for e.g. ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory"},{"type":"text","text":". Information about Pro features can be found at the end of this article."}]},{"text":"Symbol-based image extensions","anchor":"Symbol-based-image-extensions","type":"heading","level":2},{"inlineContent":[{"text":"KeyboardKit has additional images that aim to match native iOS system images, for instance ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Image\/keyboard","type":"reference"},{"text":". See ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Image","isActive":true,"type":"reference"},{"type":"text","text":" for a complete list of additional images that are provided by the library."}],"type":"paragraph"},{"inlineContent":[{"identifier":"images.jpg","type":"image"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"These images are prefixed with ","type":"text"},{"inlineContent":[{"type":"text","text":"keyboard"}],"type":"strong"},{"text":" to make them easy to find, and scale well when resized with the ","type":"text"},{"type":"strong","inlineContent":[{"text":".frame","type":"text"}]},{"text":" and ","type":"text"},{"inlineContent":[{"text":".font","type":"text"}],"type":"strong"},{"type":"text","text":" modifiers."}]},{"anchor":"👑-KeyboardKit-Pro","level":2,"text":"👑 KeyboardKit Pro","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit Pro unlocks additional image extensions that resolve to custom, vectorized assets for certain parts of the keyboard.","type":"text"}]},{"anchor":"Emojis","text":"Emojis","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks additional "},{"type":"strong","inlineContent":[{"type":"text","text":"Image"}]},{"text":" extensions that resolve to vectorized assets for the emoji key and every ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory","isActive":true},{"text":", for instance ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Image\/keyboardEmoji","isActive":true},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Image\/emojiCategory(_:)","type":"reference","isActive":true},{"type":"text","text":":"}]},{"inlineContent":[{"identifier":"images-emojis.jpg","type":"image"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Since these images are vectorized PDF assets, they will also scale well when they are resized.","type":"text"}]}]}],"metadata":{"color":{"standardColorIdentifier":"blue"},"role":"article","roleHeading":"Article","images":[{"identifier":"Page.png","type":"card"}],"title":"Images","modules":[{"name":"KeyboardKitPro"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard image engine."}],"seeAlsoSections":[{"generated":true,"title":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"]}],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/keyboardkitpro\/images-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/images-article"]}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"role":"article","title":"Feedback","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","title":"Device Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","role":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit device utilities.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"role":"article","title":"Actions","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"role":"article","abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"title":"Autocomplete","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","kind":"article","url":"\/documentation\/keyboardkitpro\/autocomplete-article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/Image":{"url":"\/documentation\/keyboardkitpro\/swiftui\/image","type":"topic","abstract":[],"title":"Image","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Image","fragments":[{"kind":"keyword","text":"extension"},{"text":" ","kind":"text"},{"kind":"identifier","preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image"}]},"Page.png":{"type":"image","identifier":"Page.png","variants":[{"traits":["1x","light"],"url":"\/images\/Page.png"}],"alt":"Page icon"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"role":"article","title":"Navigation","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"role":"article","title":"Settings","abstract":[{"text":"This article describes the KeyboardKit settings engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/settings-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"role":"article","title":"Previews","abstract":[{"text":"This article describes the KeyboardKit preview engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/previews-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/EmojiCategory":{"title":"EmojiCategory","abstract":[{"type":"text","text":"This enum defines the standard emoji categories, as well as"},{"text":" ","type":"text"},{"text":"their emojis.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/EmojiCategory","role":"symbol","navigatorTitle":[{"text":"EmojiCategory","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/keyboardkitpro\/emojicategory","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"EmojiCategory","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Routing-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit text routing engine."}],"title":"Text Routing","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/text-routing-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"title":"Layout","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/layout-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"https://github.com/KeyboardKit/KeyboardKitPro":{"type":"link","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","titleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}],"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","kind":"symbol","abstract":[{"text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro"},"images.jpg":{"type":"image","identifier":"images.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/images.jpg"}],"alt":"SF Symbol Images"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"title":"Callouts","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/callouts-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/Image/keyboard":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"keyboard","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Image\/keyboard","url":"\/documentation\/keyboardkitpro\/swiftui\/image\/keyboard","title":"keyboard"},"images-emojis.jpg":{"type":"image","alt":"Asset-based Images","identifier":"images-emojis.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/images-emojis.jpg"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/ai-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}],"title":"Proxy Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/proxy-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/State-Article":{"role":"article","title":"State","abstract":[{"text":"This article describes the KeyboardKit state engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/state-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Colors-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit color engine."}],"title":"Colors","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/colors-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"role":"article","title":"Themes","abstract":[{"text":"This article describes the KeyboardKit theme engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/themes-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"role":"article","title":"Localization","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/localization-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/Image/emojiCategory(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Image\/emojiCategory(_:)","url":"\/documentation\/keyboardkitpro\/swiftui\/image\/emojicategory(_:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"emojiCategory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EmojiCategory","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro13EmojiCategoryO"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Image","preciseIdentifier":"s:7SwiftUI5ImageV","kind":"typeIdentifier"}],"title":"emojiCategory(_:)","role":"symbol","abstract":[{"text":"An emoji category icon.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials":{"role":"article","title":"Essentials","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","type":"topic","url":"\/documentation\/keyboardkitpro\/essentials","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"role":"article","title":"Styling","abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/styling-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"role":"article","title":"External Keyboards","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"title":"Emojis","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"title":"Gestures","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/Image/keyboardEmoji":{"title":"keyboardEmoji","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/Image\/keyboardEmoji","url":"\/documentation\/keyboardkitpro\/swiftui\/image\/keyboardemoji","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardEmoji","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image","kind":"typeIdentifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","value":[{"generated":true,"title":"Features","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"]}],"path":"\/seeAlsoSections"}]}]}