{"kind":"symbol","abstract":[{"text":"This class extends ","type":"text"},{"type":"codeVoice","code":"UIInputViewController"},{"text":" with KeyboardKit","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"specific functionality."}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/autocompleteText","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/hostBundleId","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/isAutocompleteEnabled","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/isContextSyncEnabled","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/originalTextDocumentProxy","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupProError","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDocumentProxy","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textInputProxy"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/adjustTextPosition(by:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/deleteBackward()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/deleteBackward(times:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/insertText(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/openUrl(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/performAutocomplete()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/performDictation()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/performKeyboardContextSync()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/resetAutocomplete()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/selectNextLocale()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/selectionDidChange(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/selectionWillChange(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setKeyboardType(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(with:)-1jizp","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(with:)-kv25","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupPro(withLicenseKey:locales:errorDisplay:licenseConfiguration:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupPro(withLicenseKey:locales:errorDisplay:licenseConfiguration:view:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDidChange(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDidChangeAsync(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textWillChange(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/traitCollectionDidChange(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidAppear(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLayoutSubviews()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLoad()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillAppear(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillHandleDictationResult()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillRegisterSharedController()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillSetupKeyboard()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillSyncWithContext()"]},{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/LicenseConfiguration","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/ViewSetup"],"title":"Type Aliases"},{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/preview"],"title":"Type Properties"},{"title":"Enumerations","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/LicenseValidationErrorDisplay"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardInputViewController"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"inlineContent":[{"text":"Let your ","type":"text"},{"code":"KeyboardController","type":"codeVoice"},{"text":" inherit this class instead of","type":"text"},{"type":"text","text":" "},{"code":"UIInputViewController","type":"codeVoice"},{"text":" to get new lifecycle functions.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Your ","type":"text"},{"type":"codeVoice","code":"KeyboardController"},{"text":" can override any function, modify","type":"text"},{"type":"text","text":" "},{"text":"any ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","isActive":true},{"type":"text","text":" and replace any "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","type":"reference"},{"text":".","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},"sections":[],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)UIInputViewController"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardPreviews\/PreviewKeyboardInputViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSCoding","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardController","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSObject","doc:\/\/com.keyboardkit.KeyboardKitPro\/s7CVarArgP","doc:\/\/com.keyboardkit.KeyboardKitPro\/s28CustomDebugStringConvertibleP","doc:\/\/com.keyboardkit.KeyboardKitPro\/s23CustomStringConvertibleP","doc:\/\/com.keyboardkit.KeyboardKitPro\/SQ","doc:\/\/com.keyboardkit.KeyboardKitPro\/SH","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIAppearanceContainer","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIContentContainer","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIFocusEnvironment","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIStateRestoring","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextInputDelegate","doc:\/\/com.keyboardkit.KeyboardKitPro\/5UIKit23UITraitChangeObservableP","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITraitEnvironment","doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"metadata":{"role":"symbol","symbolKind":"class","roleHeading":"Class","title":"KeyboardInputViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardInputViewController"}],"modules":[{"name":"KeyboardKitPro"}],"externalID":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","navigatorTitle":[{"text":"KeyboardInputViewController","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"seeAlsoSections":[{"title":"Essentials","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardBehavior","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardController","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardBehavior","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardPreview","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardButtonPreview","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardItem"]}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/keyboardinputviewcontroller"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.keyboardkit.KeyboardKitPro/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textDidChangeAsync(_:)":{"abstract":[{"text":"This function will be called with an async delay, to","type":"text"},{"type":"text","text":" "},{"text":"give the text document proxy time to update itself.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDidChangeAsync(_:)","title":"textDidChangeAsync(_:)","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textdidchangeasync(_:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textDidChangeAsync"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(pl)UITextInput","text":"UITextInput","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/ViewSetup":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewSetup"}],"abstract":[{"type":"text","text":"This typealias represents a view setup action."}],"title":"KeyboardInputViewController.ViewSetup","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ViewSetup","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewsetup","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/ViewSetup","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textInputProxy":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textinputproxy","type":"topic","abstract":[{"text":"A custom text proxy to which text can be routed.","type":"text"}],"kind":"symbol","role":"symbol","title":"textInputProxy","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"textInputProxy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy","text":"TextInputProxy","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textInputProxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardBehavior":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardBehavior"}],"title":"KeyboardBehavior","navigatorTitle":[{"kind":"identifier","text":"KeyboardBehavior"}],"type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardbehavior","abstract":[{"type":"text","text":"This protocol can be implemented by classes that can define"},{"type":"text","text":" "},{"text":"keyboard-specific behaviors.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardBehavior","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/traitCollectionDidChange(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/traitCollectionDidChange(_:)","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/traitcollectiondidchange(_:)","title":"traitCollectionDidChange(_:)","role":"symbol","navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/performDictation()":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/performDictation()","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Perform a keyboard-initiated dictation operation."}],"role":"symbol","title":"performDictation()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"performDictation"},{"text":"()","kind":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/performdictation()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/insertText(_:)":{"abstract":[{"type":"text","text":"Insert the provided text."}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/inserttext(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/insertText(_:)","role":"symbol","title":"insertText(_:)"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/autocompleteText":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/autocompleteText","kind":"symbol","type":"topic","abstract":[{"text":"The text to use when performing autocomplete.","type":"text"}],"role":"symbol","title":"autocompleteText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"autocompleteText","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/autocompletetext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"title":"KeyboardContext","url":"\/documentation\/keyboardkitpro\/keyboardcontext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","type":"topic","abstract":[{"type":"text","text":"This class provides keyboard extensions with contextual and"},{"text":" ","type":"text"},{"text":"observable information about the keyboard extension.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/originalTextDocumentProxy":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"originalTextDocumentProxy"},{"kind":"text","text":": "},{"text":"UITextDocumentProxy","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"abstract":[{"text":"The original text document proxy.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/originalTextDocumentProxy","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/originaltextdocumentproxy","title":"originalTextDocumentProxy","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textWillChange(_:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textWillChange(_:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"textWillChange(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textWillChange"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITextInput","preciseIdentifier":"c:objc(pl)UITextInput"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"textWillChange:","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textwillchange(_:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/isContextSyncEnabled":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/iscontextsyncenabled","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isContextSyncEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/isContextSyncEnabled","type":"topic","title":"isContextSyncEnabled","abstract":[{"type":"text","text":"Whether or not context syncing is enabled."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/adjustTextPosition(by:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/adjustTextPosition(by:)","kind":"symbol","type":"topic","abstract":[{"text":"Adjust the text input cursor position.","type":"text"}],"role":"symbol","title":"adjustTextPosition(by:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"adjustTextPosition","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/adjusttextposition(by:)"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/resetAutocomplete()":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/resetAutocomplete()","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Reset the current autocomplete state."}],"role":"symbol","title":"resetAutocomplete()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetAutocomplete"},{"kind":"text","text":"()"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/resetautocomplete()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/performAutocomplete()":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/performAutocomplete()","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/performautocomplete()","role":"symbol","title":"performAutocomplete()","abstract":[{"type":"text","text":"Perform an autocomplete operation."}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"performAutocomplete","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewWillSyncWithContext()":{"abstract":[{"text":"This function is called when the controller is about","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to sync with the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/KeyboardState","type":"reference","isActive":true},{"type":"text","text":" contexts."}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillSyncWithContext","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewwillsyncwithcontext()","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillSyncWithContext()","role":"symbol","title":"viewWillSyncWithContext()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/openUrl(_:)":{"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/openUrl(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openUrl"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?)","kind":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/openurl(_:)","title":"openUrl(_:)","abstract":[{"text":"Open a certain URL","type":"text"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setKeyboardType(_:)":{"abstract":[{"type":"text","text":"Set a certain keyboard type."}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setkeyboardtype(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setKeyboardType"},{"kind":"text","text":"("},{"text":"Keyboard","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A0V0A4TypeO","text":"KeyboardType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setKeyboardType(_:)","role":"symbol","title":"setKeyboardType(_:)"},"doc://com.keyboardkit.KeyboardKitPro/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/SQ","title":"Swift.Equatable"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewDidLayoutSubviews()":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewdidlayoutsubviews()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/isAutocompleteEnabled":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/isAutocompleteEnabled","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Whether or not autocomple is enabled."}],"role":"symbol","title":"isAutocompleteEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAutocompleteEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/isautocompleteenabled"},"doc://com.keyboardkit.KeyboardKitPro/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/SH","type":"unresolvable"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/selectionWillChange(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionWillChange","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextInput","preciseIdentifier":"c:objc(pl)UITextInput"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"selectionWillChange:"}],"abstract":[],"kind":"symbol","role":"symbol","title":"selectionWillChange(_:)","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/selectionwillchange(_:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/selectionWillChange(_:)","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboard":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SystemKeyboard","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/systemkeyboard","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","abstract":[{"text":"This keyboard can be used to create alphabetic, numeric and","type":"text"},{"type":"text","text":" "},{"text":"symbolic keyboards that mimic the native iOS keyboard.","type":"text"}],"title":"SystemKeyboard","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SystemKeyboard"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/selectionDidChange(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectionDidChange"},{"kind":"text","text":"("},{"text":"UITextInput","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextInput"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/selectionDidChange(_:)","kind":"symbol","title":"selectionDidChange(_:)","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/selectiondidchange(_:)","role":"symbol","navigatorTitle":[{"text":"selectionDidChange:","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/StandardKeyboardBehavior":{"navigatorTitle":[{"text":"StandardKeyboardBehavior","kind":"identifier"}],"role":"symbol","url":"\/documentation\/keyboardkitpro\/standardkeyboardbehavior","kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/StandardKeyboardBehavior","title":"StandardKeyboardBehavior","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StandardKeyboardBehavior","kind":"identifier"}],"abstract":[{"type":"text","text":"This class defines how a standard, Western keyboard behaves."}]},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UITextInputDelegate":{"title":"UIKit.UITextInputDelegate","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITextInputDelegate","type":"unresolvable"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/state":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro0A0V","text":"Keyboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"KeyboardState","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A0V0A5StateC"}],"abstract":[{"text":"The default set of keyboard-specific state.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/state","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/state","title":"state","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/initWithCoder:":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/initwithcoder:","kind":"symbol","abstract":[],"title":"initWithCoder:","role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/deleteBackward()":{"title":"deleteBackward()","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteBackward"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/deleteBackward()","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/deletebackward()","abstract":[{"type":"text","text":"Delete backwards."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/LicenseConfiguration":{"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/licenseconfiguration","abstract":[{"type":"text","text":"This typealias represents a license configuration."}],"kind":"symbol","role":"symbol","title":"KeyboardInputViewController.LicenseConfiguration","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/LicenseConfiguration","navigatorTitle":[{"text":"LicenseConfiguration","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/LicenseValidationErrorDisplay":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LicenseValidationErrorDisplay"}],"abstract":[{"type":"text","text":"This enum defines when to display license errors."}],"title":"KeyboardInputViewController.LicenseValidationErrorDisplay","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseValidationErrorDisplay"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/licensevalidationerrordisplay","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/LicenseValidationErrorDisplay","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setup(with:)-kv25":{"role":"symbol","abstract":[{"text":"Setup KeyboardKit with a custom keyboard view.","type":"text"}],"title":"setup(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Content","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC5setup4withyxyXA_t7SwiftUI0E0RzlF7ContentL_xmfp","text":"Content","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setup(with:)-kv25","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(with:)-kv25","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","kind":"symbol","title":"KeyboardInputViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This class extends ","type":"text"},{"type":"codeVoice","code":"UIInputViewController"},{"text":" with KeyboardKit","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"specific functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/performKeyboardContextSync()":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/performKeyboardContextSync()","kind":"symbol","type":"topic","abstract":[{"text":"Perform a keyboard context sync.","type":"text"}],"role":"symbol","title":"performKeyboardContextSync()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"performKeyboardContextSync","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/performkeyboardcontextsync()"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillAppear(_:)","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewwillappear(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewDidLoad()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLoad()","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewdidload()","title":"viewDidLoad()","role":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboardItem":{"kind":"symbol","title":"SystemKeyboardItem","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardItem","role":"symbol","abstract":[{"text":"This view renders button item for a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","isActive":true},{"type":"text","text":"."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SystemKeyboardItem"}],"url":"\/documentation\/keyboardkitpro\/systemkeyboarditem","navigatorTitle":[{"text":"SystemKeyboardItem","kind":"identifier"}],"type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setupPro(withLicenseKey:locales:errorDisplay:licenseConfiguration:)":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupPro(withLicenseKey:locales:errorDisplay:licenseConfiguration:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Set up KeyboardKit Pro with a standard keyboard view."}],"role":"symbol","title":"setupPro(withLicenseKey:locales:errorDisplay:licenseConfiguration:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupPro"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withLicenseKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"locales","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"KeyboardLocale","preciseIdentifier":"s:14KeyboardKitPro0A6LocaleO","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"errorDisplay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC29LicenseValidationErrorDisplayO","text":"LicenseValidationErrorDisplay"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"licenseConfiguration"},{"text":": ","kind":"text"},{"text":"LicenseConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC20LicenseConfigurationa"},{"text":")","kind":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setuppro(withlicensekey:locales:errordisplay:licenseconfiguration:)"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textDocumentProxy":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textDocumentProxy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextDocumentProxy","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"abstract":[{"type":"text","text":"The text document proxy that is currently active."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDocumentProxy","kind":"symbol","title":"textDocumentProxy","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textdocumentproxy","role":"symbol","navigatorTitle":[{"text":"textDocumentProxy","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/services":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"services"},{"text":": ","kind":"text"},{"text":"Keyboard","preciseIdentifier":"s:14KeyboardKitPro0A0V","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"KeyboardServices","preciseIdentifier":"s:14KeyboardKitPro0A0V0A8ServicesC","kind":"typeIdentifier"}],"title":"services","type":"topic","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/services","abstract":[{"type":"text","text":"The default set of keyboard-specific services."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/services","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewDidAppear(_:)":{"navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"title":"viewDidAppear(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidAppear(_:)","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewdidappear(_:)","abstract":[]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboardButtonPreview":{"kind":"symbol","abstract":[{"type":"text","text":"This preview view can be used to preview system keyboard"},{"type":"text","text":" "},{"text":"buttons for a certain style provider.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/systemkeyboardbuttonpreview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SystemKeyboardButtonPreview"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardButtonPreview","title":"SystemKeyboardButtonPreview","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SystemKeyboardButtonPreview"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/deleteBackward(times:)":{"kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/deletebackward(times:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deleteBackward","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"times"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/deleteBackward(times:)","type":"topic","title":"deleteBackward(times:)","abstract":[{"type":"text","text":"Delete backwards a certain number of times."}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/selectNextLocale()":{"title":"selectNextLocale()","type":"topic","kind":"symbol","abstract":[{"text":"Select the next locale, if any.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"selectNextLocale","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/selectnextlocale()","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/selectNextLocale()"},"doc://com.keyboardkit.KeyboardKitPro/objc(cs)UIInputViewController":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)UIInputViewController","type":"unresolvable","title":"UIInputViewController"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setupProError":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupProError","abstract":[{"type":"text","text":"The error that was thrown during a pro setup, if any."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupProError"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setupproerror","title":"setupProError"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/hostBundleId":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/hostBundleId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hostBundleId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"hostBundleId","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/hostbundleid","abstract":[{"text":"The bundle ID of the host application, if any.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setup(with:)-1jizp":{"abstract":[{"type":"text","text":"Setup KeyboardKit with a custom keyboard view."}],"title":"setup(with:)","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setup(with:)-1jizp","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Content","kind":"genericParameter"},{"kind":"text","text":">("},{"kind":"externalParam","text":"with"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","text":"KeyboardInputViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC5setup4withyxACc_t7SwiftUI0E0RzlF7ContentL_xmfp","text":"Content"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setup(with:)-1jizp"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardController":{"abstract":[{"type":"text","text":"This protocol is used to abstract the input view controller."}],"title":"KeyboardController","navigatorTitle":[{"text":"KeyboardController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardController","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardController"}],"url":"\/documentation\/keyboardkitpro\/keyboardcontroller","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardPreviews/PreviewKeyboardInputViewController":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardPreviews\/PreviewKeyboardInputViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PreviewKeyboardInputViewController"}],"title":"KeyboardPreviews.PreviewKeyboardInputViewController","url":"\/documentation\/keyboardkitpro\/keyboardpreviews\/previewkeyboardinputviewcontroller","abstract":[],"navigatorTitle":[{"text":"PreviewKeyboardInputViewController","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard/KeyboardState":{"kind":"symbol","role":"symbol","title":"Keyboard.KeyboardState","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard\/KeyboardState","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardState"}],"abstract":[{"type":"text","text":"This type is used to specify observable keyboard states."}],"navigatorTitle":[{"text":"KeyboardState","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboard\/keyboardstate"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboardPreview":{"role":"symbol","title":"SystemKeyboardPreview","url":"\/documentation\/keyboardkitpro\/systemkeyboardpreview","kind":"symbol","abstract":[{"text":"This preview view previews how a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard"},{"text":" will","type":"text"},{"type":"text","text":" "},{"text":"render for the provided services and configuration.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SystemKeyboardPreview"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SystemKeyboardPreview"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardPreview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Keyboard":{"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboard","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Keyboard","title":"Keyboard","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Keyboard","kind":"identifier"}],"navigatorTitle":[{"text":"Keyboard","kind":"identifier"}],"abstract":[{"type":"text","text":"This namespace contains essential keyboard-related types."}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/initWithNibName:bundle:":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/initwithnibname:bundle:"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://com.keyboardkit.KeyboardKitPro/s7CVarArgP":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://com.keyboardkit.KeyboardKitPro/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.keyboardkit.KeyboardKitPro/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewWillRegisterSharedController()":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillRegisterSharedController()","kind":"symbol","type":"topic","abstract":[{"text":"This function is called when the controller is about","type":"text"},{"text":" ","type":"text"},{"text":"to register itself as the shared controller.","type":"text"}],"role":"symbol","title":"viewWillRegisterSharedController()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillRegisterSharedController"},{"kind":"text","text":"()"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewwillregistersharedcontroller()"},"doc://com.keyboardkit.KeyboardKitPro/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/preview":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/preview","abstract":[],"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/preview","title":"preview","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewWillHandleDictationResult()":{"abstract":[{"text":"This function is called to handle a dictation result","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"when returning from the main app."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillHandleDictationResult()","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewwillhandledictationresult()","title":"viewWillHandleDictationResult()","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillHandleDictationResult"},{"kind":"text","text":"()"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/setupPro(withLicenseKey:locales:errorDisplay:licenseConfiguration:view:)":{"role":"symbol","abstract":[{"type":"text","text":"Set up KeyboardKit Pro with a custom keyboard view."},{"type":"text","text":" "},{"text":"You can provide a list of locales to use, which will","type":"text"},{"type":"text","text":" "},{"type":"text","text":"be capped to the number of locales the license."}],"title":"setupPro(withLicenseKey:locales:errorDisplay:licenseConfiguration:view:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupPro","kind":"identifier"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Content"},{"kind":"text","text":">("},{"text":"withLicenseKey","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"locales"},{"text":": [","kind":"text"},{"text":"KeyboardLocale","preciseIdentifier":"s:14KeyboardKitPro0A6LocaleO","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"errorDisplay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"LicenseValidationErrorDisplay","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC29LicenseValidationErrorDisplayO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"licenseConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LicenseConfiguration","preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC20LicenseConfigurationa"},{"kind":"text","text":", "},{"text":"view","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC0E5Setupa","text":"ViewSetup"},{"kind":"text","text":"<"},{"text":"Content","kind":"typeIdentifier","preciseIdentifier":"s:14KeyboardKitPro0A19InputViewControllerC05setupC014withLicenseKey7locales12errorDisplay20licenseConfiguration4viewySS_SayAA0A6LocaleOGSgAC0i15ValidationErrorM0OyAA0I0VcxACct7SwiftUI0E0RzlF7ContentL_xmfp"},{"text":">)","kind":"text"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/setuppro(withlicensekey:locales:errordisplay:licenseconfiguration:view:)","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/setupPro(withLicenseKey:locales:errorDisplay:licenseConfiguration:view:)","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","kind":"symbol","abstract":[{"text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textDidChange(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDidChange"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITextInput","preciseIdentifier":"c:objc(pl)UITextInput"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDidChange(_:)","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textdidchange(_:)","title":"textDidChange(_:)","role":"symbol","navigatorTitle":[{"text":"textDidChange:","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/viewWillSetupKeyboard()":{"abstract":[{"text":"This function is called when a keyboard view must be","type":"text"},{"type":"text","text":" "},{"text":"created. It will by default setup a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillSetupKeyboard"},{"kind":"text","text":"()"}],"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/viewwillsetupkeyboard()","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillSetupKeyboard()","role":"symbol","title":"viewWillSetupKeyboard()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"KeyboardInputViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDocumentProxy"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/initWithCoder:","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/initWithNibName:bundle:","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/selectionDidChange(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/selectionWillChange(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDidChange(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textWillChange(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/traitCollectionDidChange(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidAppear(_:)","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLayoutSubviews()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewDidLoad()","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/viewWillAppear(_:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/objc(cs)UIInputViewController"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"replace"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyboardInputViewController"},{"kind":"text","text":" : "},{"text":"UIInputViewController","preciseIdentifier":"c:objc(cs)UIInputViewController","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"traitCollectionDidChange:","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1traitCollectionDidChange(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1traitCollectionDidChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"traitCollectionDidChange:","kind":"identifier"}]},{"value":"textWillChange:","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textWillChange(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textWillChange:"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textWillChange(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLayoutSubviews()\/title","op":"replace","value":"viewDidLayoutSubviews"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLayoutSubviews()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1selectionWillChange(_:)\/title","value":"selectionWillChange:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"selectionWillChange:"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1selectionWillChange(_:)\/fragments"},{"op":"replace","value":"selectionDidChange:","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1selectionDidChange(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1selectionDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"selectionDidChange:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"kind":"identifier","text":"KeyboardInputViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillAppear:"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewWillAppear(_:)\/fragments"},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLoad()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidLoad()\/fragments"},{"value":"textDocumentProxy","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDocumentProxy\/title"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDocumentProxy\/fragments","value":[{"kind":"identifier","text":"textDocumentProxy"}],"op":"replace"},{"value":"viewDidAppear:","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidAppear(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1viewDidAppear(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDidChange(_:)\/title","value":"textDidChange:","op":"replace"},{"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDidChange(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"textDidChange:","kind":"identifier"}]}]}]}