{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"This article describes the KeyboardKit preview engine.","type":"text"}],"metadata":{"modules":[{"name":"KeyboardKitPro"}],"roleHeading":"Article","role":"article","images":[{"identifier":"Page.png","type":"card"}],"color":{"standardColorIdentifier":"blue"},"title":"Previews"},"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"kind":"article","seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Features"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article"},"variants":[{"paths":["\/documentation\/keyboardkitpro\/previews-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/previews-article"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"SwiftUI previews are a great way to work on your project in Xcode without having to launch an app all the time. Just update your views and models, and the preview will update."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit has preview-specific services and state, that can be used in your previews. This makes it easy to set up and preview your keyboard-specific views directly in Xcode."}]},{"inlineContent":[{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","isActive":true,"type":"reference"},{"type":"text","text":" unlocks system keyboard and theme previews. Information about Pro features can be found at the end of this article."}],"type":"paragraph"},{"type":"heading","anchor":"KeyboardPreviews-namespace","level":2,"text":"KeyboardPreviews namespace"},{"type":"paragraph","inlineContent":[{"text":"KeyboardKit has a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardPreviews","isActive":true,"type":"reference"},{"text":" namespace that contains preview-related services and state. The name doesn’t match the group name, since “Previews” conflicts with SwiftUI.","type":"text"}]},{"inlineContent":[{"type":"text","text":"For instance, the "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","type":"reference","isActive":true},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/preview"},{"type":"text","text":" can be used as a dummy context, and the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController"},{"text":" ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/preview"},{"type":"text","text":" as a dummy input controller."}],"type":"paragraph"},{"inlineContent":[{"text":"These static, preview-specific services and state values simplify creating previews for views that use KeyboardKit-specific types.","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"How to use preview-specific state and services","anchor":"How-to-use-preview-specific-state-and-services"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Consider this view, that takes a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","type":"reference"},{"text":" init parameter and looks for a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext"},{"type":"text","text":" in the environment:"}]},{"syntax":"swift","type":"codeListing","code":["struct CustomView: View {","","    init(actionHandler: KeyboardActionHandler) {","        self.actionHandler = actionHandler","    }","","    private var actionHandler: KeyboardActionHandler","","    @EnvironmentObject","    private var context: KeyboardContext","","    var body: some View {","        VStack {","            Button(\"Trigger backspace\") {","                actionHandler.handle(.release, on: .backspace)","            }","            Button(\"Delete text in the proxu\") {","                context.textDocumentProxy.deleteBackwards()","            }","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"To preview this view, just inject a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler\/preview"},{"type":"text","text":" action handler in the initializer and a "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/preview","type":"reference"},{"type":"text","text":" keyboard context as an environment object:"}]},{"code":["#Preview {","","    CustomView(actionHandler: .preview)","        .environmentObject(KeyboardContext.preview)","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can take a look at the source code of the various views in the library for inspiration."}]},{"anchor":"👑-KeyboardKit-Pro","text":"👑 KeyboardKit Pro","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"overridingTitle":"KeyboardKit Pro","isActive":true,"type":"reference","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","overridingTitleInlineContent":[{"text":"KeyboardKit Pro","type":"text"}]},{"type":"text","text":" unlocks powerful system keyboard previews, that can be used to preview different locales, configurations and themes."}]},{"tabs":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardPreview"},{"type":"text","text":" that can be used to preview a full "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard"},{"text":" in many different ways, for instance by passing in a custom locale or theme","type":"text"}]},{"numberOfColumns":2,"type":"row","columns":[{"size":1,"content":[{"inlineContent":[{"identifier":"systemkeyboardpreview.jpg","type":"image"}],"type":"paragraph"}]},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"systemkeyboardpreview-theme.jpg"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This preview is intended to be used in the main app, to for instance provide interactive previews in a settings screen. Since it draws a full keyboard with all interactions enabled, avoid displaying more one at a time."}]}],"title":"SystemKeyboardPreview"},{"title":"SystemKeyboardButtonPreview","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro also unlocks a more lightweight "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardButtonPreview"},{"text":" that can be used to preview many buttons at once, for instance to preview multiple styles or ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","isActive":true,"type":"reference"},{"text":"s at once:","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"systemkeyboardbuttonpreview-350.jpg"}]},{"type":"paragraph","inlineContent":[{"text":"Unlike the ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardPreview","isActive":true,"type":"reference"},{"type":"text","text":", this view just renders a very lightweight button preview, and is perfect for being used in style or theme pickers, to quickly visualize how certain button types look for a certain configuration, etc."}]}]}],"type":"tabNavigator"}],"kind":"content"}],"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}],"title":"Proxy Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/proxy-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","kind":"symbol","title":"KeyboardInputViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This class extends ","type":"text"},{"type":"codeVoice","code":"UIInputViewController"},{"text":" with KeyboardKit","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"specific functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"role":"article","title":"Navigation","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","title":"Device Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","role":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit device utilities.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"role":"article","title":"Feedback","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","kind":"symbol","abstract":[{"text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardAction":{"title":"KeyboardAction","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardAction"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardAction"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction","abstract":[{"type":"text","text":"This enum defines keyboard-specific actions that correspond"},{"type":"text","text":" "},{"text":"to actions that can be found on various keyboards.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardaction"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Routing-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit text routing engine."}],"title":"Text Routing","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/text-routing-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"role":"article","abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"title":"Autocomplete","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","kind":"article","url":"\/documentation\/keyboardkitpro\/autocomplete-article","images":[{"type":"card","identifier":"Page.png"}]},"systemkeyboardpreview.jpg":{"identifier":"systemkeyboardpreview.jpg","variants":[{"url":"\/images\/systemkeyboardpreview.jpg","traits":["1x","light"]}],"alt":"System Keyboard Preview - Turkish","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardPreviews":{"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardPreviews","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"KeyboardPreviews","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardpreviews","title":"KeyboardPreviews","abstract":[{"text":"This namespace defines preview-related types for many types.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardPreviews"}],"role":"symbol","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"role":"article","title":"Themes","abstract":[{"text":"This article describes the KeyboardKit theme engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/themes-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardContext"}],"title":"KeyboardContext","url":"\/documentation\/keyboardkitpro\/keyboardcontext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardContext"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext","type":"topic","abstract":[{"type":"text","text":"This class provides keyboard extensions with contextual and"},{"text":" ","type":"text"},{"text":"observable information about the keyboard extension.","type":"text"}],"kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardContext/preview":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preview"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A7ContextC","text":"KeyboardContext","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardContext\/preview","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardcontext\/preview","title":"preview","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"title":"Callouts","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/callouts-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler":{"abstract":[{"text":"This protocol can be implemented by classes that can handle","type":"text"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardAction"},{"type":"text","text":"s."}],"kind":"symbol","title":"KeyboardActionHandler","navigatorTitle":[{"text":"KeyboardActionHandler","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"KeyboardActionHandler","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardactionhandler","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials":{"role":"article","title":"Essentials","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","type":"topic","url":"\/documentation\/keyboardkitpro\/essentials","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"Page.png":{"alt":"Page icon","variants":[{"url":"\/images\/Page.png","traits":["1x","light"]}],"identifier":"Page.png","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/State-Article":{"role":"article","title":"State","abstract":[{"text":"This article describes the KeyboardKit state engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/state-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardActionHandler/preview":{"abstract":[],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardActionHandler\/preview","title":"preview","url":"\/documentation\/keyboardkitpro\/keyboardactionhandler\/preview","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" is "},{"type":"codeVoice","code":"KeyboardPreviews.PreviewKeyboardActionHandler"},{"text":".","type":"text"}]},"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"preview","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14KeyboardKitPro0A13ActionHandlerP","kind":"typeIdentifier","text":"KeyboardActionHandler"}]},"systemkeyboardpreview-theme.jpg":{"identifier":"systemkeyboardpreview-theme.jpg","variants":[{"traits":["1x","light"],"url":"\/images\/systemkeyboardpreview-theme.jpg"}],"alt":"System Keyboard Preview - Theme","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/ai-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"role":"article","title":"External Keyboards","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"systemkeyboardbuttonpreview-350.jpg":{"alt":"System Keyboard Button Preview","variants":[{"traits":["1x","light"],"url":"\/images\/systemkeyboardbuttonpreview-350.jpg"}],"identifier":"systemkeyboardbuttonpreview-350.jpg","type":"image"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"role":"article","title":"Localization","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/localization-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"title":"Layout","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/layout-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"title":"Emojis","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"role":"article","title":"Settings","abstract":[{"text":"This article describes the KeyboardKit settings engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/settings-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboardButtonPreview":{"kind":"symbol","abstract":[{"type":"text","text":"This preview view can be used to preview system keyboard"},{"type":"text","text":" "},{"text":"buttons for a certain style provider.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/systemkeyboardbuttonpreview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SystemKeyboardButtonPreview"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardButtonPreview","title":"SystemKeyboardButtonPreview","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SystemKeyboardButtonPreview"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTheme":{"url":"\/documentation\/keyboardkitpro\/keyboardtheme","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeyboardTheme"}],"abstract":[{"type":"text","text":"This struct defines a keyboard-specific theme."}],"title":"KeyboardTheme","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTheme","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardTheme","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboard":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SystemKeyboard","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/systemkeyboard","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard","abstract":[{"text":"This keyboard can be used to create alphabetic, numeric and","type":"text"},{"type":"text","text":" "},{"text":"symbolic keyboards that mimic the native iOS keyboard.","type":"text"}],"title":"SystemKeyboard","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SystemKeyboard"}],"role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Colors-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit color engine."}],"title":"Colors","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/colors-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"role":"article","title":"Actions","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Images-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard image engine."}],"title":"Images","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/images-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"https://github.com/KeyboardKit/KeyboardKitPro":{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"type":"link","url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"title":"Gestures","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SystemKeyboardPreview":{"role":"symbol","title":"SystemKeyboardPreview","url":"\/documentation\/keyboardkitpro\/systemkeyboardpreview","kind":"symbol","abstract":[{"text":"This preview view previews how a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboard"},{"text":" will","type":"text"},{"type":"text","text":" "},{"text":"render for the provided services and configuration.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SystemKeyboardPreview"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SystemKeyboardPreview"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SystemKeyboardPreview"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/preview":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyboardInputViewController","preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)KeyboardInputViewController","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/preview","abstract":[],"role":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/preview","title":"preview","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"role":"article","title":"Styling","abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/styling-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":null,"op":"add"},{"value":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Features","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":"KeyboardInputViewController","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title"},{"value":[{"text":"KeyboardInputViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}