{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"text":"KeyboardKit has ways to check various keyboard state, such as if a keyboard is enabled in System Settings, if ","type":"text"},{"type":"strong","inlineContent":[{"text":"Full Access","type":"text"}]},{"text":" is enabled, if the keyboard is currently being used, etc.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"This information can be used to make an app help users to set up their keyboard properly.","type":"text"}],"type":"paragraph"},{"level":2,"type":"heading","anchor":"Keyboard-state","text":"Keyboard state"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The observable "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStateContext"},{"type":"text","text":" can be used to observe the state of any keyboard:"}]},{"syntax":"swift","code":["struct MyView: View {","","    @StateObject","    var state = KeyboardStateContext(bundleId: \"com.myapp.keyboard\")","","    var body: some View {","        VStack {","            Text(\"Enabled: \\(state.isKeyboardEnabled.description)\")","            Text(\"Active: \\(state.isKeyboardActive.description)\")","            Text(\"Full Access: \\(state.isFullAccessEnabled.description)\")","        }","    }","} "],"type":"codeListing"},{"inlineContent":[{"text":"Since the context is observable, any state changes will immediately cause the view to refresh.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The context supports bundle ID wildcards, which means that you can inspect multiple keyboards with a single instance:"}],"type":"paragraph"},{"code":["@StateObject","var state = KeyboardStateContext(bundleId: \"com.myapp.*\")"],"syntax":null,"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStateInspector","type":"reference"},{"type":"text","text":" protocol that powers the context can be implemented by any type, to make it able to inspect the state of a keyboard at any time."}]},{"anchor":"Views","type":"heading","level":2,"text":"Views"},{"tabs":[{"title":"KeyboardState.Label","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A keyboard state "},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardState\/Label","isActive":true,"type":"reference"},{"type":"text","text":" can be used to display any keyboard state, for instance if the keyboard has been enabled in System Settings, if Full Access is enabled, etc."}]},{"code":["struct MyView: View {","","    @StateObject","    var state = KeyboardStateContext(bundleId: \"com.myapp.keyboard\")","","    var body: some View {","        KeyboardState.Label(","            isEnabled: state.isKeyboardEnabled,","            enabledText: \"Keyboard is enabled\",","            disabledText: \"Keyboard is disabled\",","        )","    }","} "],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"The view can be wrapped in a ","type":"text"},{"type":"codeVoice","code":"Link"},{"text":" or ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettingsLink","type":"reference"},{"text":" to link to System Settings. It supports custom texts, icons, etc.","type":"text"},{"type":"text","text":" "},{"text":"and can be styled with a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardState\/LabelStyle","isActive":true},{"text":" or by applying a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardStateLabelStyle(_:)","type":"reference","isActive":true},{"type":"text","text":" view modifier."}]}]}],"type":"tabNavigator"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article"},{"type":"text","text":" article for more information about how styling is handled in KeyboardKit."}]}]}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit state engine."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"generated":true,"title":"Features"}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"variants":[{"paths":["\/documentation\/keyboardkitpro\/state-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/state-article"]}],"metadata":{"role":"article","images":[{"type":"card","identifier":"Page.png"}],"roleHeading":"Article","title":"State","color":{"standardColorIdentifier":"blue"},"modules":[{"name":"KeyboardKitPro"}]},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"role":"article","title":"Localization","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/localization-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"role":"article","title":"Navigation","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","title":"Device Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","role":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit device utilities.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Text-Routing-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit text routing engine."}],"title":"Text Routing","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/text-routing-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Images-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard image engine."}],"title":"Images","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/images-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"title":"Gestures","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"role":"article","title":"Themes","abstract":[{"text":"This article describes the KeyboardKit theme engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/themes-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"role":"article","title":"Styling","abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/styling-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"role":"article","title":"Settings","abstract":[{"text":"This article describes the KeyboardKit settings engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/settings-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/ai-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Colors-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit color engine."}],"title":"Colors","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/colors-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/SwiftUI/View/keyboardStateLabelStyle(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardStateLabelStyle","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:14KeyboardKitPro0A5StateV","kind":"typeIdentifier","text":"KeyboardState"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14KeyboardKitPro0A5StateV10LabelStyleV","text":"LabelStyle","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"abstract":[{"text":"Apply a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardState\/LabelStyle","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/SwiftUI\/View\/keyboardStateLabelStyle(_:)","kind":"symbol","url":"\/documentation\/keyboardkitpro\/swiftui\/view\/keyboardstatelabelstyle(_:)","title":"keyboardStateLabelStyle(_:)","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"role":"article","title":"Actions","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStateContext":{"abstract":[{"type":"text","text":"This context can be used to observe the enabled state of"},{"type":"text","text":" "},{"text":"a keyboard extension.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"KeyboardStateContext","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KeyboardStateContext","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardstatecontext","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStateContext","role":"symbol","title":"KeyboardStateContext"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"role":"article","title":"Previews","abstract":[{"text":"This article describes the KeyboardKit preview engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/previews-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"role":"article","abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"title":"Autocomplete","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","kind":"article","url":"\/documentation\/keyboardkitpro\/autocomplete-article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardState/LabelStyle":{"title":"KeyboardState.LabelStyle","url":"\/documentation\/keyboardkitpro\/keyboardstate\/labelstyle","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LabelStyle","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardState\/LabelStyle","abstract":[{"text":"This style can be used to modify the visual style of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardState\/Label","type":"reference"},{"text":" component.","type":"text"}],"navigatorTitle":[{"text":"LabelStyle","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"role":"article","title":"External Keyboards","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"title":"Callouts","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/callouts-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"role":"article","title":"Feedback","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"Page.png":{"alt":"Page icon","variants":[{"url":"\/images\/Page.png","traits":["1x","light"]}],"type":"image","identifier":"Page.png"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardSettingsLink":{"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardSettingsLink","title":"KeyboardSettingsLink","abstract":[{"type":"text","text":"This link can be used to navigate to System Settings."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardSettingsLink","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardsettingslink","navigatorTitle":[{"kind":"identifier","text":"KeyboardSettingsLink"}],"type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials":{"role":"article","title":"Essentials","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","type":"topic","url":"\/documentation\/keyboardkitpro\/essentials","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}],"title":"Proxy Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/proxy-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"title":"Layout","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/layout-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardStateInspector":{"role":"symbol","navigatorTitle":[{"text":"KeyboardStateInspector","kind":"identifier"}],"abstract":[{"text":"This protocol can be implemented by classes that must be","type":"text"},{"type":"text","text":" "},{"text":"able to check the enabled state of a keyboard extension.","type":"text"}],"title":"KeyboardStateInspector","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardStateInspector","kind":"identifier"}],"type":"topic","url":"\/documentation\/keyboardkitpro\/keyboardstateinspector","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardStateInspector","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardState/Label":{"title":"KeyboardState.Label","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}],"abstract":[{"text":"This label can be used to show the currently enabled","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"state for a keyboard."}],"navigatorTitle":[{"text":"Label","kind":"identifier"}],"url":"\/documentation\/keyboardkitpro\/keyboardstate\/label","role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardState\/Label","type":"topic","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"title":"Emojis","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","kind":"symbol","abstract":[{"text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Features"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}