{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Custom iOS keyboard extensions use "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UITextDocumentProxy","isActive":true},{"type":"text","text":" to interact with the currently selected text field, e.g. to insert or delete text, move the input cursor, etc."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Keyboard extensions will however "},{"type":"emphasis","inlineContent":[{"text":"not","type":"text"}]},{"type":"text","text":" send text to text fields "},{"inlineContent":[{"text":"within","type":"text"}],"type":"emphasis"},{"type":"text","text":" your keyboard by default. Even if you focus on a text field within the keyboard, the text will still be sent to the selected text field in the currently active app."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"These limitations make it hard to implement features that require text input in the keyboard, like emoji search, and AI-based features."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit therefore adds ways to make text routing easier. "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","type":"reference"},{"type":"text","text":" has a custom "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textInputProxy","isActive":true},{"type":"text","text":" that can be set to route text to any other text field."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"👑 "},{"identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","type":"reference","isActive":true},{"text":" unlocks even more text routing utils, like a ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField","isActive":true,"type":"reference"},{"text":" that automatically registers and unregisters as the input proxy when it gets and loses focus. Information about Pro features can be found at the end of this article.","type":"text"}]},{"anchor":"How-to-route-text-with-KeyboardKit","text":"How to route text with KeyboardKit","level":2,"type":"heading"},{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UITextDocumentProxy","type":"reference"},{"type":"text","text":" has a native textDocumentProxy, which is how a keyboard extension by default interacts with the currently selected text field, e.g. to insert or delete text, move the input cursor, etc."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","isActive":true},{"text":" has a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textInputProxy"},{"text":" that can be set to override ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDocumentProxy","type":"reference"},{"type":"text","text":" as the main text document proxy. Setting it will cause any text you type to be sent to that proxy instead of the original one."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Just set "},{"isActive":true,"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textInputProxy","type":"reference"},{"type":"text","text":" to "},{"type":"strong","inlineContent":[{"type":"text","text":"nil"}]},{"text":" to restore the original proxy and start routing text back to the main application. You can also always access the original proxy with ","type":"text"},{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/originalTextDocumentProxy","type":"reference","isActive":true},{"text":".","type":"text"}]},{"level":2,"type":"heading","anchor":"👑-KeyboardKit-Pro","text":"👑 KeyboardKit Pro"},{"type":"paragraph","inlineContent":[{"type":"text","text":"KeyboardKit Pro unlocks text input components that automatically register and unregister themselves as the main text input proxy when they receive and lose focus:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField","isActive":true},{"text":" wraps a native text field and can be used for single-line text inputs.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView","isActive":true,"type":"reference"},{"type":"text","text":" wraps a native text view and can be used for multi-line text inputs."}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that you can also use the "},{"type":"reference","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField","isActive":true},{"text":" text field configuration block to enable multiline support on later iOS versions.","type":"text"}]},{"inlineContent":[{"type":"text","text":"Both views support SwiftUI focus state, and have a custom focused view modifier that lets you provide a custom done button that will slide in when the view is focused:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["struct CustomKeyboardToolbar: View {","","    unowned var controller: KeyboardInputViewController","","    @State ","    private var text = \"\"","","    @FocusState ","    private var isTextFieldFocused","","    var body: some View {","        if hasFullAccess {","            KeyboardTextField(text: $text, controller: controller) {","                $0.placeholder = \"Type here...\" \/\/ UITextField config","            }","            .focused($isTextFieldFocused) {","                Image(systemName: \"xmark.circle.fill\")","            }","        }","    }","}"]},{"style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"This view requires Full Access and will automatically disable itself when it’s disabled, due to an iOS bug that causes a crash when using text field while Full Access is disabled.","type":"text"}]}],"type":"aside"}],"kind":"content"}],"abstract":[{"type":"text","text":"This article describes the KeyboardKit text routing engine."}],"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Text-Routing-Article","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"],"title":"Features","generated":true}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro"]]},"variants":[{"paths":["\/documentation\/keyboardkitpro\/text-routing-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/text-routing-article"]}],"metadata":{"modules":[{"name":"KeyboardKitPro"}],"title":"Text Routing","role":"article","roleHeading":"Article","images":[{"identifier":"Page.png","type":"card"}],"color":{"standardColorIdentifier":"blue"}},"references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Gestures-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit gesture engine."}],"title":"Gestures","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/gestures-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTextView":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextView","role":"symbol","abstract":[{"text":"This view can be used to type in a keyboard extension.","type":"text"}],"url":"\/documentation\/keyboardkitpro\/keyboardtextview","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeyboardTextView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardTextView"}],"kind":"symbol","title":"KeyboardTextView","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textInputProxy":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textinputproxy","type":"topic","abstract":[{"text":"A custom text proxy to which text can be routed.","type":"text"}],"kind":"symbol","role":"symbol","title":"textInputProxy","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"textInputProxy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy","text":"TextInputProxy","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textInputProxy"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Emojis-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit emoji engine."}],"title":"Emojis","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/emojis-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/originalTextDocumentProxy":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"originalTextDocumentProxy"},{"kind":"text","text":": "},{"text":"UITextDocumentProxy","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"abstract":[{"text":"The original text document proxy.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/originalTextDocumentProxy","kind":"symbol","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/originaltextdocumentproxy","title":"originalTextDocumentProxy","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/State-Article":{"role":"article","title":"State","abstract":[{"text":"This article describes the KeyboardKit state engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/state-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"Page.png":{"alt":"Page icon","type":"image","identifier":"Page.png","variants":[{"traits":["1x","light"],"url":"\/images\/Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Previews-Article":{"role":"article","title":"Previews","abstract":[{"text":"This article describes the KeyboardKit preview engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/previews-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/UIKit/UITextDocumentProxy":{"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/UIKit\/UITextDocumentProxy","fragments":[{"text":"extension","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:objc(pl)UITextDocumentProxy","text":"UITextDocumentProxy"}],"navigatorTitle":[{"kind":"identifier","text":"UITextDocumentProxy"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/keyboardkitpro\/uikit\/uitextdocumentproxy","title":"UITextDocumentProxy","kind":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController/textDocumentProxy":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textDocumentProxy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextDocumentProxy","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextDocumentProxy"}],"abstract":[{"type":"text","text":"The text document proxy that is currently active."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController\/textDocumentProxy","kind":"symbol","title":"textDocumentProxy","url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller\/textdocumentproxy","role":"symbol","navigatorTitle":[{"text":"textDocumentProxy","kind":"identifier"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Dictation-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit dictation engine."}],"title":"Dictation","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/dictation-article","kind":"article"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Styling-Article":{"role":"article","title":"Styling","abstract":[{"text":"This article describes the KeyboardKit styling engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/styling-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Colors-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit color engine."}],"title":"Colors","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/colors-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardInputViewController":{"url":"\/documentation\/keyboardkitpro\/keyboardinputviewcontroller","kind":"symbol","title":"KeyboardInputViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardInputViewController","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardInputViewController"}],"abstract":[{"text":"This class extends ","type":"text"},{"type":"codeVoice","code":"UIInputViewController"},{"text":" with KeyboardKit","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"specific functionality."}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardInputViewController","role":"symbol"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Localization-Article":{"role":"article","title":"Localization","abstract":[{"text":"This article describes the KeyboardKit localization engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/localization-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Essentials":{"role":"article","title":"Essentials","abstract":[{"text":"This article describes the essential parts of KeyboardKit.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","type":"topic","url":"\/documentation\/keyboardkitpro\/essentials","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Device-Article":{"kind":"article","url":"\/documentation\/keyboardkitpro\/device-article","title":"Device Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","role":"article","type":"topic","abstract":[{"text":"This article describes the KeyboardKit device utilities.","type":"text"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Callouts-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit callout engine."}],"title":"Callouts","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/callouts-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Feedback-Article":{"role":"article","title":"Feedback","abstract":[{"text":"This article describes the KeyboardKit feedback engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/feedback-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Navigation-Article":{"role":"article","title":"Navigation","abstract":[{"text":"This article describes the KeyboardKit navigation engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/navigation-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","kind":"symbol","abstract":[{"text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/KeyboardTextField":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyboardTextField","kind":"identifier"}],"title":"KeyboardTextField","navigatorTitle":[{"text":"KeyboardTextField","kind":"identifier"}],"abstract":[{"text":"This view can be used to type in a keyboard extension.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/KeyboardTextField","url":"\/documentation\/keyboardkitpro\/keyboardtextfield"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Themes-Article":{"role":"article","title":"Themes","abstract":[{"text":"This article describes the KeyboardKit theme engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/themes-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/AI-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit AI support capabilities."}],"title":"AI Support","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/ai-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Layout-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit layout engine."}],"title":"Layout","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/layout-article","kind":"article","images":[{"identifier":"Page.png","type":"card"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Autocomplete-Article":{"role":"article","abstract":[{"text":"This article describes the KeyboardKit autocomplete engine.","type":"text"}],"title":"Autocomplete","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","kind":"article","url":"\/documentation\/keyboardkitpro\/autocomplete-article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Settings-Article":{"role":"article","title":"Settings","abstract":[{"text":"This article describes the KeyboardKit settings engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/settings-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Images-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit keyboard image engine."}],"title":"Images","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/images-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"https://github.com/KeyboardKit/KeyboardKitPro":{"type":"link","identifier":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","titleInlineContent":[{"type":"text","text":"KeyboardKit Pro"}],"url":"https:\/\/github.com\/KeyboardKit\/KeyboardKitPro","title":"KeyboardKit Pro"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Actions-Article":{"role":"article","title":"Actions","abstract":[{"text":"This article describes the KeyboardKit action engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/actions-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/Proxy-Article":{"role":"article","abstract":[{"type":"text","text":"This article describes the KeyboardKit proxy engine and its utilities."}],"title":"Proxy Utilities","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/proxy-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/External-Keyboards-Article":{"role":"article","title":"External Keyboards","abstract":[{"text":"This article describes the KeyboardKit external keyboard engine.","type":"text"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","type":"topic","url":"\/documentation\/keyboardkitpro\/external-keyboards-article","kind":"article","images":[{"type":"card","identifier":"Page.png"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Features","generated":true,"identifiers":["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Essentials","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Actions-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/AI-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Autocomplete-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Callouts-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Colors-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Device-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Dictation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Emojis-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/External-Keyboards-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Feedback-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Gestures-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Images-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Layout-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Localization-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Navigation-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Previews-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Proxy-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Settings-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/State-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Styling-Article","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/Themes-Article"]}]},{"value":"textDocumentProxy","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDocumentProxy\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController~1textDocumentProxy\/fragments","value":[{"text":"textDocumentProxy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/title","value":"KeyboardInputViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1KeyboardInputViewController\/fragments","value":[{"text":"KeyboardInputViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}