{"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy"]]},"variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/autocorrectiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/autocorrectiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autocorrectionType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextAutocorrectionType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextAutocorrectionType"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"UITextInputTraits.autocorrectionType","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autocorrectionType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UITextAutocorrectionType","preciseIdentifier":"c:@E@UITextAutocorrectionType"}],"role":"symbol","externalID":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy(py)autocorrectionType","title":"autocorrectionType","modules":[{"name":"KeyboardKitPro"}],"navigatorTitle":[{"text":"autocorrectionType","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/autocorrectionType","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/autocorrectionType":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"autocorrectionType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextAutocorrectionType","text":"UITextAutocorrectionType"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/keyboardkitpro\/textinputproxy\/autocorrectiontype","title":"autocorrectionType","navigatorTitle":[{"text":"autocorrectionType","kind":"identifier"}],"identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/autocorrectionType"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TextInputProxy","kind":"identifier"}],"title":"TextInputProxy","navigatorTitle":[{"kind":"identifier","text":"TextInputProxy"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","abstract":[{"text":"This class can be used to route typed text from the main","type":"text"},{"type":"text","text":" "},{"type":"text","text":"app to text fields within the keyboard extension."}],"url":"\/documentation\/keyboardkitpro\/textinputproxy","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","kind":"symbol","abstract":[{"text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"autocorrectionType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"autocorrectionType","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UITextAutocorrectionType","preciseIdentifier":"c:@E@UITextAutocorrectionType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"autocorrectionType","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"autocorrectionType","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1autocorrectionType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1autocorrectionType\/fragments","value":[{"kind":"identifier","text":"autocorrectionType"}]},{"value":"TextInputProxy","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title"},{"value":[{"kind":"identifier","text":"TextInputProxy"}],"op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments"}]}]}