{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentInputMode","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentInputMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextInputMode","text":"UITextInputMode","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/documentinputmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/keyboardkitpro\/textinputproxy\/documentinputmode"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy"]]},"metadata":{"title":"documentInputMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"documentInputMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextInputMode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextInputMode"},{"kind":"text","text":"?"}],"modules":[{"name":"KeyboardKitPro"}],"externalID":"c:@M@KeyboardKitPro@objc(cs)TextInputProxy(py)documentInputMode","navigatorTitle":[{"text":"documentInputMode","kind":"identifier"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UITextDocumentProxy.documentInputMode"},{"type":"text","text":"."}],"kind":"symbol","references":{"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy/documentInputMode":{"title":"documentInputMode","abstract":[],"role":"symbol","navigatorTitle":[{"text":"documentInputMode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"documentInputMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextInputMode","preciseIdentifier":"c:objc(cs)UITextInputMode"},{"kind":"text","text":"?"}],"url":"\/documentation\/keyboardkitpro\/textinputproxy\/documentinputmode","kind":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy\/documentInputMode","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro/TextInputProxy":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TextInputProxy","kind":"identifier"}],"title":"TextInputProxy","navigatorTitle":[{"kind":"identifier","text":"TextInputProxy"}],"role":"symbol","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro\/TextInputProxy","abstract":[{"text":"This class can be used to route typed text from the main","type":"text"},{"type":"text","text":" "},{"type":"text","text":"app to text fields within the keyboard extension."}],"url":"\/documentation\/keyboardkitpro\/textinputproxy","kind":"symbol","type":"topic"},"doc://com.keyboardkit.KeyboardKitPro/documentation/KeyboardKitPro":{"role":"collection","kind":"symbol","abstract":[{"text":"KeyboardKit helps you create custom keyboard extensions with Swift and SwiftUI.","type":"text"}],"url":"\/documentation\/keyboardkitpro","type":"topic","identifier":"doc:\/\/com.keyboardkit.KeyboardKitPro\/documentation\/KeyboardKitPro","title":"KeyboardKitPro"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"documentInputMode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"documentInputMode"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"UITextInputMode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextInputMode"},{"text":" * ","kind":"text"},{"text":"documentInputMode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"documentInputMode","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentInputMode\/title","op":"replace"},{"op":"replace","value":[{"text":"documentInputMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy~1documentInputMode\/fragments"},{"value":"TextInputProxy","op":"replace","path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/title"},{"value":[{"kind":"identifier","text":"TextInputProxy"}],"path":"\/references\/doc:~1~1com.keyboardkit.KeyboardKitPro~1documentation~1KeyboardKitPro~1TextInputProxy\/fragments","op":"replace"}]}]}